### ISSUE TITLE
Migration DTD/properties -> FTL

### ISSUE THREAD

**Issue by Pike** [Pike/cl-next#13]
# Input Data

The Migration process uses
- `en-US` ftl
- `l10n` ftl existing state
- legacy `l10n` data in DTDs, properties, etc
- Operations
# Operations

The current list of operations are
- [x] COPY with unescaping of &lt; and \u00a0
- [x] PLACABLE REFORMAT, &brandShortName;, %S, %1$S, { name }, #1
- [x] PLURAL reconstruction, analyze existing plural string, map PluralForms.jsm numbers to CLDR keys, iterate over strings, create selector
- [x] CONCAT all of the above, plus literals
- [ ] DELETE id_or_trait, in case we want to delete existing messages or one of their traits
# Message Generation

Messages are generated with an extended AST, which creates the AST of a message with the operations and data above.
# Message Merge

Message merge takes the new (and to be deleted) messages, along with their attribution. It then executes a merge algorithm for each author and commits that.

The merge algorithm takes the en-US ftl as template, to create sections, comments, and order messages. It creates a minimal edit based on top of the (existing or newly created) l10n ftl file. It doesn't reformat outside of messages that are given by the operations for the current author.

In case of doubt, strings are inserted last into the section they belong to.

Much of this will be implemented as part of [python-l20n](https://github.com/l20n/python-l20n).

**Comment by Pike** [comment]
stas and I got together and came up with a plan. Editing the initial comment to reflect our outcome from today.

**Comment by stasm** [comment]
Here's an example of the extended AST that Pike and I talked about yesterday.  Given the following current translation in `/mobile/android/locales/en-US/chrome/aboutDownloads.properties`:

```
downloadMessage.deleteAll=Delete this download?;Delete #1 downloads?
```

…we want to get this on the output:

```
delete-all-message = { $num ->
    [1]     Delete this download?
   *[other] Delete { $num } downloads?
}
```

The extended AST combines the nodes from the FTL syntax with special nodes describing operations needed to transform the input into the output.  For clarity I prefixed all special fields with `__`:

``` json
{
    "type": "Entity",
    "id": {
        "type": "Identifier",
        "name": "delete-all-message"
    },
    "value": {
        "__op": "Plural Reconstruction",
        "__source": {
            "file": "/mobile/android/locales/en-US/chrome/aboutDownloads.properties",
            "id": "downloadMessage.deleteAll"
        },
        "__selector": {
            "type": "ExternalArgument",
            "name": "num"
        },
        "__forEachVariant": [
            {
                "__op": "Placeable Reformat",
                "__from": "#1",
                "__to": [
                    {
                        "type": "ExternalArgument",
                        "name": "num"
                    }
                ]
            }
        ]
    }
}
```

The special _operation_ nodes are denoted by having the `__op` field.  They must return valid FTL AST subtrees.

**Comment by stasm** [comment]
The above is encoded in JSON but we talked about the possibility of encoding directly in Python code:

``` python
"__forEachVariant": (
    lambda var: PlaceableReformat(var, from="#1", to=FTL.ExternalArgument("num")),
)
```

**Comment by Pike** [comment]
Looks good to me.

I was only surprised to see __to being a list. Did you have a rationale for that?

**Comment by stasm** [comment]
Yes, in FTL's AST placeables are always a list, in case you wanted to have an implicit list like `{ $user1, $user2 }`.
