### ISSUE TITLE
Decision: Django templates or Jinja?

### ISSUE THREAD

**Issue by Pike** [Pike/cl-next#34]
elmo uses django, pontoon jinja

**Comment by Pike** [comment]
@mathjazz isn't sure he actually wants to stick to jinja2 templates, they've been a bit of pain using other django libraries.

Assigning to him to evaluate that.

**Comment by mathjazz** [comment]
Confirming that there's nothing that prevents us from moving Ponton to Django templates.

**Comment by Pike** [comment]
Filed [bug 1314975](https://bugzilla.mozilla.org/show_bug.cgi?id=1314975) to migrate pontoon, then.
