### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Pike** [Pike/cl-next#8]
- [x] Inline code comments
- [x] docstrings
  - [x] src/lib/dom
  - [x] src/lib/observer
  - [x] src/lib/format
  - [x] src/intl
  - [x] src/ftl
- [x] usage docs (restructured text, gecko RTD)

**Comment by stasm** [comment]
@Pike what is the purpose of the _integration docs_ (the last bullet point on the list above)?  Looking at my notes, we're done with the documentation. \o/

**Comment by stasm** [comment]
As per discussion with @Pike, I removed the checkbox about integration docs as its purpose was unclear.
